name: Documentation 📚
description: Suggest an improvement to the documentation
title: '[Docs]: '
labels:
  - documentation
  - triage
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for taking the time to suggest an improvement to the documentation!
  - type: textarea
    id: description
    attributes:
      label: Documentation Description
      description: A clear and concise description of the documentation issue.
      placeholder: |
        The documentation for...
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: Please describe how you would like to improve the documentation.
      placeholder: |
        I would like to see...
    validations:
      required: true
